### ISSUE TITLE
code for computing network measures?

### ISSUE THREAD

**Issue by Ronggui** [dgarcia-eu/IPP_Twitter_2016#1]
Are the codes computing network measures such as D-cores, bow-tie structures etc. available? Thanks.

**Comment by dgarcia-eu** [comment]
You can compute the coreness values and the bow-tie structure with standard libraries like igraph. For this article, we processed the network with programs we developed in C for our local computing setup and there was no scientific innovation in that implementation. These would not work in general, so for that reason they are not redistributed in this repository (as well as the raw network data).
